# Generated by Django 5.0.7 on 2025-09-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'General Consultation'), ('followup', 'Follow-up Visit'), ('checkup', 'Routine Check-up'), ('emergency', 'Emergency Consultation'), ('specialist', 'Specialist Consultation')], default='consultation', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_notes',
            field=models.TextField(blank=True, help_text='Please describe your symptoms or reason for visit'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
